---
# Install Redis server
- name: "Install Redis server"
  apt: name=redis-server

# Bind Redis server to all interfaces
- name: "Bind Redis server to all interfaces"
  lineinfile: dest=/etc/redis/redis.conf 
              state=present 
              regexp="^#?bind" 
              line="#bind 127.0.0.1"
  notify:
    - "Restart Redis"

# Ensure Redis server is running
- name: "Ensure Redis server is running"
  action: service name=redis-server state=started
