---
- name: Create the app group
  sudo: yes
  group: name=app
  
- name: Create an app user
  sudo: yes
  user: shell=/bin/bash name=app comment="App User" group=app

- name: Create a deploy user
  sudo: yes
  user: shell=/bin/bash name=deploy comment="Deploy User" group=app groups=sudo,app

- name: Add key for app user
  authorized_key: user=app key="{{ lookup('file', './secret/access_key.pub') }}"

- name: Add key for deploy user
  authorized_key: user=deploy key="{{ lookup('file', './secret/access_key.pub') }}"
