common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

production: &env
  <<: *common
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  database: <%= ENV['DB_NAME'] %>
  host: 127.0.0.1

development:
  <<: *common
  database: catarse_development

test:
  <<: *common
  database: catarse_test
