---
- name: Purge database
  hosts: staging-app
  user: root
  gather_facts: true
  sudo: true

  vars:
    domain_name: "staging.{{app_name}}.com"
    environment_name: staging
    rails_environment_name: production
    mail_method: letter_opener

  vars_files:
    - vars/common.yml
    - secret/staging.yml

  tasks:
    - name: Restart postgresql
      service: name=postgresql state=restarted
      
    - name: Destroy database
      sudo_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        encoding: 'UTF-8'
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'
        template: 'template0'
        state: absent
