---
- name: Provision App
  hosts: staging-app
  user: root
  gather_facts: true
  sudo: true

  vars:
    domain_name: "{{app_name}}.com"
    environment_name: staging
    rails_environment_name: production

  vars_files:
    - vars/common.yml
    - secret/staging.yml

  roles:
    - user
    - common
    - environment_vars
    - ufw
    - ruby-2.1.3
    - nginx
    - postgres
    - redis
    - sidekiq
    - backup
